feat: Add Server Context Support
Snazzah/slash-create pull request #621
Opened 2024-06-27 22:31 UTC by KitsuneDev

This is a straightforward solution to #620, implementing a `CommandContext.serverContext` property that can be defined by the Server.
`CommandContext.serverContext` is naturally a generic of the default type `unknown`, leaving the user responsible for determining its type and handling casts accordingly. This fits with the use case of CloudFlare Workers, as its structure changes depending on how bindings are defined.

Consequently, this PR enables using Durable Objects and D1 databases in bots. Through the use of [Durable Objects](https://developers.cloudflare.com/durable-objects/), many things that could only previously be achieved in stateful workflows can now be achieved in serverless.

2024-06-27 22:41 UTC, KitsuneDev commented
By the way, I can also work on documenting this if you'd like. This is a super minimal implementation that I came up with in about an hour to allow me to use D1 in a bot of mine.

2024-06-28 00:53 UTC, Snazzah commented
I like the implementation, I'd also like to extend this implementation towards the other contexts, you'd probably be better to extend from `BaseInteractionContext` and move the context down the line.

Another thing I'd like to do as a whole cloudflare worker focused update is to automatically get the variables for the discord app ID, token, and public key while responding to a request, since the `env` can only be fetched on request.

2024-06-28 00:54 UTC, Snazzah requested changes

2024-06-28 00:54 UTC, Snazzah commented on src/servers/cfworker.ts
> +          { cloudflare: true, ...env }
```suggestion
          { server: 'cloudflare', ...env }
```

This would be better so other contexts can use the same prop.

2024-07-04 16:46 UTC, KitsuneDev commented
This does look better! I'll keep playing to see if I can find a way to make type inference work better in a subsequent PR

2024-07-05 23:25 UTC, Snazzah commented
Cool, the only thing to do now is to put server contexts in `BaseInteractionContext` so things like autocomplete can make use of it.

2024-07-15 19:09 UTC, merged